

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQubeServer'
    scannerMode: 'Other'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: sonar-buildbreaker@8
  inputs:
    SonarQube: 'SonarQubeServer'

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'